name: 'Build and Push Image'
on:
  workflow_dispatch:
    inputs:
      stable:
        type: boolean
        description: should be uploaded with the 'latest' tag
        default: false
jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}
      - name: evaulate tag
        id: eval
        run: |
          if [[ "${{ inputs.stable }}" == "true" ]]; then
            echo "setting tag to latest..."
            echo "::set-output name=tag::latest"
          else
            echo "setting tag to ${{ github.run_id }}..."
            echo "::set-output name=tag::alpha-${{ github.run_number }}"
          fi
      - name: build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: quay.io/school3/school3-bot:${{ steps.eval.outputs.tag }}
